### ISSUE TITLE
How to solve memory issues?

### ISSUE THREAD

**Issue by hirasso** [tobimori/kirby-blurhash#10]
Hi there! 

If I delete my thumbhash cache folder, my site is overwhelmed on a few pages by the many calls to `$image->thumbhashUri()`, resulting in a memory allocation error. What's the recommended solution to solve this? Does kirby-thumbhash provide some kind of cli command to re-generate thumbhashes for all images on a site?

**Comment by tobimori** [comment]
besides that this is the repository for blurhash (not thumbhash) - no. you can set a smaller sampleMaxSize and make sure the thumbs that are encoded are correctly downsized: https://github.com/tobimori/kirby-thumbhash#options-1

**Comment by hirasso** [comment]
Oh haha, sorry. I keep mixing up blurhash and thumbhash 😅 Feel free to move this issue over to the correct repo if possible.

In the docs, you are mentioning something about needing to use the _original_ image for the thumbhash creation. Is that true or can I do `$image->resize(100)->thumbhashUri()`?

**Comment by tobimori** [comment]
That won't work because file methods are not applicable to a FileVersion object (which the resize returns). The sampleMaxSize in the config should be automatically used for resizing in the plugin.

**Comment by hirasso** [comment]
So I'll just hope that the cache folder will never be deleted ;)
