### ISSUE TITLE
fails with indexed and optimized image with low colors

### ISSUE THREAD

**Issue by bnomei** [tobimori/kirby-blurhash#8]
![10965](https://github.com/tobimori/kirby-blurhash/assets/3265642/fc582594-f18a-4310-8b29-7f9275317e72)

**Comment by tobimori** [comment]
I assume this is an issue with the respective library, https://github.com/kornrunner/php-blurhash. 
As a workaround, my Thumbhash plugin seems to handle this image just fine.
